import { ClerkProvider } from "@clerk/nextjs";
import "../globals.css";
import { Ubuntu } from "next/font/google";
import Navbar from "@/components/Shared/Navbar";
import { currentUser } from "@clerk/nextjs";

const ubuntu = Ubuntu({ subsets: ["latin"], weight: "400" });
const user = await currentUser();

export const metadata = {
  title: "CropIntel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={ubuntu.className}>
          <Navbar user={user} />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
