import { ClerkProvider } from "@clerk/nextjs";
import "../globals.css";
import { Ubuntu } from "next/font/google";
import Navbar from "@/components/Shared/Navbar";

const ubuntu = Ubuntu({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Harvestify",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={ubuntu.className}>
          <Navbar />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
